OrganizAPI:
  path: /api/v4/organizations
  add:
    { "name": "utuytut",
      "parent": "qpG8DsWSaY8FAwWxN", "sort_no": 100, "hidden": false,
      "space": "NhnKCEchFReJbgqZM"}
  update:
    {
      "$set": {
        "name": "testccc",
        "parent": "qpG8DsWSaY8FAwWxN","sort_no": 100,"hidden": false,
        "space": "NhnKCEchFReJbgqZM" } }